### ISSUE TITLE
[Bug] Requirements fail to install under Python 3.12

### ISSUE THREAD

**Issue by Packetdancer** [Hybris95/UEX-Trader#117]
This is a fairly easy one; aiohttp versions earlier than 3.9.0 evidently cannot build wheel under Python 3.12. If you happen to have Python 3.12 installed, as a result, pip horfs up a hairball when you try to install requirements.

Changing UEX-Trader to require aiohttp 3.9.0 instead of 3.8.4 corrects the issue.

**Comment by Hybris95** [comment]
I only tried 3.11 Python for now, I may do a pass with 3.12 Python and make sure the versions used for 3.12 are also compatible with 3.11.

To make it simple, I prefer staying on fixed versions of dependencies and make sure they are fully compatible with the version of Python set (if it can be compatible with both versions then I will also put 3.12 as compatible)

The more versions of Python I have the more tests I will have to do (and so takes more time for the workflows to pass).
But the idea to go for higher version of Python is good, since #109 too :D
